framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 0
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\Message\UserNotificationMessage: async
            App\Message\ServiceMethodCallMessage: async

            
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
